# 🛠️ Preparación de los Datos

## Librerias a utilizar
* Pandas 🐼
* matplotlib
* seaborn
* scikit-learn
* imbalanced-learn

In [28]:
import pandas as pd

In [29]:
df = pd.read_csv('Datos_Telecom_Tratados_1.csv')
df

,ID_Cliente,Evasion,Genero,Adulto_Mayor,Pareja,Dependientes,Meses_Contrato,Servicio_Telefonico,Lineas_Multiples,Servicio_Internet,...,Proteccion_Dispositivo,Soporte_Tecnico,Streaming_TV,Streaming_Peliculas,Contrato,Facturacion_Electronica,Metodo_Pago,Cargo_Mensual,Cargo_Total,Cuentas_Diarias
0,0002-ORFBO,0,Femenino,0,1,1,9,1,No,DSL,...,No,Sí,Sí,No,Un año,1,Cheque por correo,65.60,593.30,2.19
1,0003-MKNFE,0,Masculino,0,0,0,9,1,Sí,DSL,...,No,No,No,Sí,Mes a mes,0,Cheque por correo,59.90,542.40,2.00
2,0004-TLHLJ,1,Masculino,0,0,0,4,1,No,Fibra óptica,...,Sí,No,No,No,Mes a mes,1,Cheque electrónico,73.90,280.85,2.46
3,0011-IGKFF,1,Masculino,1,1,0,13,1,No,Fibra óptica,...,Sí,No,Sí,Sí,Mes a mes,1,Cheque electrónico,98.00,1237.85,3.27
4,0013-EXCHZ,1,Femenino,1,1,0,3,1,No,Fibra óptica,...,No,Sí,Sí,No,Mes a mes,1,Cheque por correo,83.90,267.40,2.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,9987-LUTYD,0,Femenino,0,0,0,13,1,No,DSL,...,No,Sí,No,No,Un año,0,Cheque por correo,55.15,742.90,1.84
7028,9992-RRAMN,1,Masculino,0,1,0,22,1,Sí,Fibra óptica,...,No,No,No,Sí,Mes a mes,1,Cheque electrónico,85.10,1873.70,2.84
7029,9992-UJOEL,0,Masculino,0,0,0,2,1,No,DSL,...,No,No,No,No,Mes a mes,1,Cheque por correo,50.30,92.75,1.68
7030,9993-LHIEB,0,Masculino,0,1,1,67,1,No,DSL,...,Sí,Sí,No,Sí,Dos años,0,Cheque por correo,67.85,4627.65,2.26
7031,9995-HOTOH,0,Masculino,0,1,1,63,0,Sin servicio telefónico,DSL,...,Sí,No,Sí,Sí,Dos años,0,Cheque electrónico,59.00,3707.60,1.97

## Eliminación columnas Irrelevantes

In [30]:
df = df.drop(columns=['ID_Cliente', 'Cuentas_Diarias'])
df

,Evasion,Genero,Adulto_Mayor,Pareja,Dependientes,Meses_Contrato,Servicio_Telefonico,Lineas_Multiples,Servicio_Internet,Seguridad_Online,Respaldo_Online,Proteccion_Dispositivo,Soporte_Tecnico,Streaming_TV,Streaming_Peliculas,Contrato,Facturacion_Electronica,Metodo_Pago,Cargo_Mensual,Cargo_Total
0,0,Femenino,0,1,1,9,1,No,DSL,No,Sí,No,Sí,Sí,No,Un año,1,Cheque por correo,65.60,593.30
1,0,Masculino,0,0,0,9,1,Sí,DSL,No,No,No,No,No,Sí,Mes a mes,0,Cheque por correo,59.90,542.40
2,1,Masculino,0,0,0,4,1,No,Fibra óptica,No,No,Sí,No,No,No,Mes a mes,1,Cheque electrónico,73.90,280.85
3,1,Masculino,1,1,0,13,1,No,Fibra óptica,No,Sí,Sí,No,Sí,Sí,Mes a mes,1,Cheque electrónico,98.00,1237.85
4,1,Femenino,1,1,0,3,1,No,Fibra óptica,No,No,No,Sí,Sí,No,Mes a mes,1,Cheque por correo,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,Femenino,0,0,0,13,1,No,DSL,Sí,No,No,Sí,No,No,Un año,0,Cheque por correo,55.15,742.90
7028,1,Masculino,0,1,0,22,1,Sí,Fibra óptica,No,No,No,No,No,Sí,Mes a mes,1,Cheque electrónico,85.10,1873.70
7029,0,Masculino,0,0,0,2,1,No,DSL,No,Sí,No,No,No,No,Mes a mes,1,Cheque por correo,50.30,92.75
7030,0,Masculino,0,1,1,67,1,No,DSL,Sí,No,Sí,Sí,No,Sí,Dos años,0,Cheque por correo,67.85,4627.65
7031,0,Masculino,0,1,1,63,0,Sin servicio telefónico,DSL,Sí,Sí,Sí,No,Sí,Sí,Dos años,0,Cheque electrónico,59.00,3707.60

## Encoding

In [31]:
df_codificado = pd.get_dummies(df, drop_first=True, dtype=int)

In [32]:
print("Dimensiones antes de codificar:", df.shape)
print("Dimensiones DESPUÉS de codificar:", df_codificado.shape)

Dimensiones antes de codificar: (7032, 20)
Dimensiones DESPUÉS de codificar: (7032, 31)

In [33]:
# Damos un vistazo a las primeras filas para ver la transformación
df_codificado.head()

,Evasion,Adulto_Mayor,Pareja,Dependientes,Meses_Contrato,Servicio_Telefonico,Facturacion_Electronica,Cargo_Mensual,Cargo_Total,Genero_Masculino,...,Soporte_Tecnico_Sí,Streaming_TV_Sin servicio de internet,Streaming_TV_Sí,Streaming_Peliculas_Sin servicio de internet,Streaming_Peliculas_Sí,Contrato_Mes a mes,Contrato_Un año,Metodo_Pago_Cheque por correo,Metodo_Pago_Tarjeta de crédito (automática),Metodo_Pago_Transferencia bancaria (automática)
0,0,0,1,1,9,1,1,65.6,593.30,0,...,1,0,1,0,0,0,1,1,0,0
1,0,0,0,0,9,1,0,59.9,542.40,1,...,0,0,0,0,1,1,0,1,0,0
2,1,0,0,0,4,1,1,73.9,280.85,1,...,0,0,0,0,0,1,0,0,0,0
3,1,1,1,0,13,1,1,98.0,1237.85,1,...,0,0,1,0,1,1,0,0,0,0
4,1,1,1,0,3,1,1,83.9,267.40,0,...,1,0,1,0,0,1,0,1,0,0

## Verificación de la Proporción de Cancelación (Churn)

In [34]:
# Clientes que cancelaron -> 0
# Clientes que no cancelaron -> 1
conteo = df['Evasion'].value_counts()
conteo

Evasion
0    5163
1    1869
Name: count, dtype: int64

In [35]:
# Obtenemos la proporción en porcentaje
proporcion_conteo = df['Evasion'].value_counts(normalize=True)*100
proporcion_conteo

Evasion
0    73.421502
1    26.578498
Name: proportion, dtype: float64

## Balanceo de Clases

In [36]:
from imblearn.over_sampling import SMOTE

In [37]:
# Separamos X (Variables predictorias) y 'y' (Variable Objetivo)
X = df_codificado.drop('Evasion', axis=1)
y = df_codificado['Evasion']

In [38]:
# Antes de aplicar SMOTE
# Clientes que cancelaron -> 0
# Clientes que no cancelaron -> 1
y.value_counts()

Evasion
0    5163
1    1869
Name: count, dtype: int64

In [39]:
# Usamos random_state=42 para que los datos sintéticos sean reproducibles
smote = SMOTE(random_state=42)

# Aplicamos Tecnicas de Balanceo
X_balanceado, y_balanceado = smote.fit_resample(X, y)

In [40]:
# Despues de Smote
y_balanceado.value_counts()

Evasion
0    5163
1    5163
Name: count, dtype: int64

In [41]:
print(f"Nuevas dimensiones de X: {X_balanceado.shape}")
print(f"Nuevas dimensiones de y: {y_balanceado.shape}")

Nuevas dimensiones de X: (10326, 30)
Nuevas dimensiones de y: (10326,)

## Normalización o Estandarización

In [42]:
from sklearn.preprocessing import StandardScaler

# Instanciamos el estandarizador
scaler = StandardScaler()

In [43]:
columnas_numericas = ['Meses_Contrato', 'Cargo_Mensual', 'Cargo_Total']

In [44]:
X_balanceado[columnas_numericas] = scaler.fit_transform(X_balanceado[columnas_numericas])
X_balanceado[columnas_numericas].head()

   Meses_Contrato  Cargo_Mensual  Cargo_Total
0       -0.779489      -0.085026    -0.665748
1       -0.779489      -0.283648    -0.689020
2       -0.988026       0.204196    -0.808605
3       -0.612659       1.043986    -0.371050
4       -1.029734       0.552657    -0.814755

# 🤖 Modelado Predictivo

# 📋 Interpretación y Conclusiones